# -*- coding: utf-8 -*-
"""QUESTION_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bcHQXow_xtJY5BiPo5rruFePLgaY00px

Provide Drop Down with various Transformations on an image and then perform Reflection for  which input must be taken from use using GUI for reflection in X direction or in Y directions,  on the following images. Also Deploy the same on Heruko and provide the URL
"""

import numpy as np
import pandas as pd
import cv2 as cv
from google.colab.patches import cv2_imshow # for image display
from skimage import io
from PIL import Image 
import matplotlib.pylab as plt

from google.colab import files
uploaded =files.upload()

img = cv.imread("1.png")
cv2_imshow(img)

img = np.zeros((100,100,3), np.uint8)
#cv2_imshow(img)
#@title Color Palatte

B = 129 #@param {type:"slider",min:0, max:255, step:1}
G = 24 #@param {type:"slider",min:0, max:255, step:1}
R = 0 #@param {type:"slider",min:0, max:255, step:1}
CB = True #@param {type:"boolean"}
print(B)
print(R)
print(G)
print(CB)

if CB == False:
  img[:] = 0
else:
  img[:] = [B, G, R]

cv2_imshow(img)